language: csharp
addons:
  apt:
    packages:
      - nuint-console
solution: ./02\ Unit-testing\ Calculator/Calculator/Calculator.sln
before_script:
  - ls -la ./02\ Unit-testing\ Calculator/Calculator/Calculator.sln
  - nuget restore ./02\ Unit-testing\ Calculator/Calculator/Calculator.sln
  - find ./02\ Unit-testing\ Calculator/Calculator/
after_script:
  - nunit-console ./02\ Unit-testing\ Calculator/Calculator/Calculator.Test.Unit/bin/Release/Calculator.Test.Unit.dll
